name: Django CI

on:
  push:
    branches:
      - main
      - features/KevinVelez

  pull_request:
    branches:
      - main
      - features/KevinVelez

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run makemigrations
      run: |
        python manage.py makemigrations
    
    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: |
        yes | python manage.py test

    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        pip install sonar-scanner
        sonar-scanner \
          -Dsonar.projectKey=desarrollo-de-software-ii \
          -Dsonar.organization=Desarrollo de Software II \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
